### ISSUE TITLE
TypeError: Cannot call method 'substr' of undefined in lib/source-map/source-node.js:94:33

### ISSUE THREAD

**Issue by willmruzek** [mozilla/source-map#138]
I'm having trouble with my build that uses webpack and the 6to5-loader.

From the stack trace below it looks like there's a problem with consuming an already existing source map...

Could this be a result of incompatibility between source-map versions?

**Stacktrace**

``` bash
/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:161
            if(isError) throw e;
                              ^
TypeError: Cannot call method 'substr' of undefined
    at Function.<anonymous> (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:94:33)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:478:10)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:78:26)
    at Source.OriginalSource (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/OriginalSource.js:39:21)
    at DependenciesBlock.onModuleBuild (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:279:19)
    at nextLoader (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:253:25)
    at /Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:15
    at Object.context.callback (/Users/wmruzek/cp/dev/cpclient/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:146:14)
    at Object.module.exports (/Users/wmruzek/cp/dev/cpclient/node_modules/6to5-loader/index.js:23:10)
```

**npm ls source-map**

``` bash
$ npm ls source-map
shinobi@0.0.1 /Users/wmruzek/cp/dev/cpclient
├─┬ 6to5@1.11.8
│ ├─┬ regenerator-6to5@0.7.2
│ │ └─┬ commoner@0.10.0
│ │   └─┬ recast@0.7.5
│ │     └── source-map@0.1.32
│ ├─┬ regexpu@0.3.0
│ │ └─┬ recast@0.8.8
│ │   └── source-map@0.1.32
│ ├── source-map@0.1.40
│ └─┬ source-map-support@0.2.8
│   └── source-map@0.1.32
├─┬ bower@1.3.12
│ └─┬ handlebars@2.0.0
│   └─┬ uglify-js@2.3.6
│     └── source-map@0.1.40
├─┬ css-loader@0.9.0
│ └── source-map@0.1.40
├─┬ exports-loader@0.6.2
│ └── source-map@0.1.40
├─┬ gulp-ng-annotate@0.3.4
│ ├─┬ ng-annotate@0.11.0
│ │ └── source-map@0.1.40
│ └─┬ vinyl-sourcemaps-apply@0.1.4
│   └── source-map@0.1.40
├─┬ gulp-uglify@1.0.1
│ ├─┬ uglify-js@2.4.15
│ │ └── source-map@0.1.34
│ └─┬ vinyl-sourcemaps-apply@0.1.4
│   └── source-map@0.1.40
├─┬ karma@0.12.24
│ └── source-map@0.1.40
├─┬ protractor@1.4.0
│ └─┬ source-map-support@0.2.8
│   └── source-map@0.1.32
├─┬ regenerator@0.6.10
│ └─┬ recast@0.9.3
│   └── source-map@0.1.32
└─┬ webpack@1.4.13
  ├─┬ uglify-js@2.4.15
  │ └── source-map@0.1.34
  └─┬ webpack-core@0.4.8
    └── source-map@0.1.40
```

I've put in an issue with webpack here: https://github.com/webpack/webpack/issues/578

**Comment by Lexicality** [comment]
I've just somehow managed to trigger this myself - this time with sourcemaps coming from grunt-contrib-uglify. I'm trying to find out why, but I agree with @sokra that this should not crash with an unhelpful error message.
