### ISSUE TITLE
Error with sass files and ampersand

### ISSUE THREAD

**Issue by mlankenau** [mozilla/source-map#254]
Hi there,

I am running into problem with source-map. It is used in brunch that is used in my elixir/phoenix project. The problem is about bootstrap_sass files. It fails with a mapping error when the ampersand syntax is being used. E.g.:

```
.blockquote-reverse,
blockquote.pull-right {
  padding-right: 15px;
  padding-left: 0;
  border-right: 5px solid $blockquote-border-color;
  border-left: 0;
  text-align: right;

  // Account for citation
  footer,
  small,
  .small {
    &:before { content: ''; }     // <<<<<=========== here I got the error
    &:after {
      content: '\00A0 \2014'; // nbsp, em dash
    }
  }
}
```

I am not the biggest Javascript dev, otherwise I would try to fix it on my own and provide a PR.

**Comment by DenisRichartz** [comment]
I have encountered the same Problem, though it does work on one of the machines i tested it on.
The problem seems to be a negative column in the original file if an ampersand is used.

I did a really dirty fix by adding a *return;* before the validation checks in the *SourceMapGenerator.prototype._validateMapping* function in *node_modules/source-map/lib/source-map-generator.js* on the machine it did not work on.

**Comment by calebshay** [comment]
I just ran into this as well.  Tracked it down to an issue with sass-brunch-2.10.2.  Rolling back to sass-brunch-2.10.1 fixed it.

Other's are having the same issue.  https://github.com/brunch/sass-brunch/issues/141

**Comment by hvalcourtSerdy** [comment]
I have the same problem and I dont use sass-bruch-2.10.2
`webpack building...
/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-map-generator.js:277
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":4045},"source":"/Volumes/Git/serdy-web-core/src/styles/bootstrap/mixins/_hover.scss","original":{"line":22,"column":-46},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-node.js:345:13
    at SourceNode_walk [as walk] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-node.js:224:9)
    at SourceNode_walk [as walk] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_walk [as walk] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/Volumes/Git/serdy-web-core/node_modules/source-map/lib/source-node.js:336:8)
    at ConcatSource.proto.sourceAndMap (/Volumes/Git/serdy-web-core/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:32)
    at /Volumes/Git/serdy-web-core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:65:35
    at Array.map (native)
    at /Volumes/Git/serdy-web-core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:52:85
    at Array.forEach (native)
    at Compilation.<anonymous> (/Volumes/Git/serdy-web-core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:51:12)
    at Compilation.applyPlugins1 (/Volumes/Git/serdy-web-core/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Volumes/Git/serdy-web-core/node_modules/webpack/lib/Compilation.js:639:11)
    at Compilation.applyPluginsAsyncSeries (/Volumes/Git/serdy-web-core/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Volumes/Git/serdy-web-core/node_modules/webpack/lib/Compilation.js:635:10)
    at next (/Volumes/Git/serdy-web-core/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/index.js:341:4)
    at Compilation.applyPluginsAsyncSeries (/Volumes/Git/serdy-web-core/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/Volumes/Git/serdy-web-core/node_modules/webpack/lib/Compilation.js:631:9)
    at next (/Volumes/Git/serdy-web-core/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/index.js:313:5)
    at /Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at /Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/index.js:297:6
    at /Volumes/Git/serdy-web-core/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16`

**Comment by tromey** [comment]
My understanding from the above is that this is a bug in sass, so I'm closing this report.

**Comment by Slapbox** [comment]
I'm not using SASS and I get this error when trying to use webpack obfuscator to obfuscate my javascript project.
