### ISSUE TITLE
SourceNode.fromStringWithSourceMap throws an error on mappings with null sources

### ISSUE THREAD

**Issue by nholland94** [mozilla/source-map#302]
Here is an example stacktrace from the exception that is thrown.

```
<omitted>/source-map/lib/util.js:33
  var match = aUrl.match(urlRegexp);
                   ^
TypeError: Cannot call method 'match' of null
    at urlParse (<omitted>/source-map/lib/util.js:33:20)
    at Object.join (<omitted>source-map/lib/util.js:148:18)
    at addMappingWithCode (<omitted>/source-map/lib/source-node.js:155:18)
    at Function.<anonymous> (<omitted>source-map/lib/source-node.js:92:11)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (<omitted>/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (<omitted>/source-map/lib/source-node.js:86:24)
    at <omitted>...

```

**Comment by jkrems** [comment]
Since there were no further reports of this, I'll go ahead an close this issue.
