### ISSUE TITLE
Error: original.line and original.column are not numbers

### ISSUE THREAD

**Issue by wvankuipers** [mozilla/source-map#304]
***Note:*** This is a report coming from [webpack-sources#28](https://github.com/webpack/webpack-sources/issues/28)

**Issue**
When running the source-map package agains a project with Backbone.Marionette (also reports for Vue and possibly more frameworks) the package generates an error and exits.

**Steps to reproduce**
I created a small repo [here](https://github.com/wvankuipers/webpack-test) that has this issue. When debugging the issue I pinpointed the culprit to be [this line](https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L16) in the Backbone.Marionette library:

    typeof define === 'function' && define.amd ? define(['backbone', 'underscore', 'backbone.radio'], factory) :

And then specifically:

    define(['backbone', 'underscore', 'backbone.radio'], factory)

Even removing the rest of that file's content and leaving only this part there will cause source-map to fail with the error above... Removing this line and source-map wil succeed. 

**Expected behaviour**
Create the package as expected, this can be tested by setting `sourceMap: null` to the configuration of the babel-minify-webpack-plugin package. (this will disable the source-map execution)

**Actual behaviour**
```frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (frontend/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (frontend/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (frontend/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (frontend/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)```

**Comment by loopmode** [comment]
The problem seems to stem from `webpack-sources@1.0.2`. Keeping it at `1.0.1` should help as a workaround.

**Comment by rostislav1229** [comment]
@loopmode  Thank you. you're great.

**Comment by glixlur** [comment]
So is this a problem with `webpack-sources` or `source-map`?

**Comment by jussikinnula** [comment]
I'm also interested on this one.

**Comment by wvankuipers** [comment]
@tromey Is there any chance that someone can look into this?

**Comment by tromey** [comment]
I think this error is intentional, to catch a case where the library was being called incorrectly.  See #265.

So, my first thought is that the fix belongs elsewhere.  I'm open to arguments to the contrary, but I'm afraid you'd have to walk me through it a bit -- like, why is the caller calling into source-map this way?  Which part of the condition is believed to be wrong and why?

**Comment by Reinmar** [comment]
This affects my projects as well.

If anyone wants to reproduce it, there seems to be a DUP in https://github.com/webpack/webpack/issues/6131 describing steps to do so.

Also, you can reproduce this in my project:

```
git clone git@github.com:ckeditor/ckeditor5-build-classic.git
cd ckeditor5-build-classic
git co stable
```

Now, edit `package.json` to remove the hardcoded `webpack-sources`. And then:

```
npm i
./node_modules/.bin/webpack
```

Result:

```
/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
    at SourceMapSource.node (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
    at /workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (native)
    at ConcatSource.node (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (/workspace/test/ckeditor5-build-classic/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
    at getTaskForFile (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (native)
    at /workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
    at Array.forEach (native)
    at Compilation.<anonymous> (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/Compilation.js:670:11)
    at next (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at next (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.<anonymous> (/workspace/test/ckeditor5-build-classic/node_modules/babel-minify-webpack-plugin/dist/index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/Compilation.js:666:10)
    at Compilation.applyPluginsAsyncSeries (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/Compilation.js:662:9)
    at Compilation.applyPluginsAsyncSeries (/workspace/test/ckeditor5-build-classic/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/workspace/test/ckeditor5-build-classic/node_modules/webpack/lib/Compiler.js:504:17)
```

**Comment by mitchhentges** [comment]
BTW, for a simpler reproduce environment, the official [`electron-webpack-quick-start`](https://github.com/electron-userland/electron-webpack-quick-start) can be used:

1. `git clone https://github.com/electron-userland/electron-webpack-quick-start`
2. `cd electron-webpack-quick-start`
3. `npm i`
4. `npm run compile`

For future reference, this is reproducible on the current most-recent commit (`0f0ec413af42174600b35d19762edd11f7c423e2`)

**Comment by sgaloux** [comment]
Is there a valid workaround?

**Comment by trusktr** [comment]
After updating to Webpack 4 and removing babel-minify-webpack-plugin I no longer get this error.

**Comment by evilebottnawi** [comment]
Problem in babel-minify plugin https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68. Issue can be close here. thanks!

**Comment by z3by** [comment]
worked for me.

```
npm i terser@4.0.0
npm run build
```

**Comment by ordinaryparksee** [comment]
@z3by I would like to say you saved my soul
