### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by lixinxin93** [mozilla/source-map#311]
hello, I'm using gulp-sourcemaps v1.12.0, and now has an error in your code at source-map/lib/source-map-consumer.js:72: 
```
  [exec]   let consumer = null;
     [exec]   ^^^
     [exec] 
     [exec] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

node version is v4.8.1.  

(English is not my native language, I hope I made it clear.  )

**Comment by lixinxin93** [comment]
Here is ths error stack:
```
 [exec] /myProject/node_modules/gulp-sourcemaps/node_modules/source-map/lib/source-map-consumer.js:72
     [exec]   let consumer = null;
     [exec]   ^^^
     [exec] 
     [exec] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
     [exec]     at exports.runInThisContext (vm.js:53:16)
     [exec]     at Module._compile (module.js:373:25)
     [exec]     at Object.Module._extensions..js (module.js:416:10)
     [exec]     at Module.load (module.js:343:32)
     [exec]     at Function.Module._load (module.js:300:12)
     [exec]     at Module.require (module.js:353:17)
     [exec]     at require (internal/module.js:12:17)
     [exec]     at Object.<anonymous> (/myProject/node_modules/gulp-sourcemaps/node_modules/source-map/source-map.js:7:29)
     [exec]     at Module._compile (module.js:409:26)
     [exec]     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by fitzgen** [comment]
Thanks for filing an issue.

> node version is v4.8.1.

Your node version is too low to run `source-map >= 0.7.0`: https://github.com/mozilla/source-map/blob/master/package.json#L57
