### ISSUE TITLE
the lib binary-search has a bug

### ISSUE THREAD

**Issue by FTAndy** [mozilla/source-map#343]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
RangeError: Maximum call stack size exceeded
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:24:25)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:59:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:59:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:44:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:59:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:44:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:44:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:44:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:59:14)
    at recursiveSearch (/data/app/mobile-html5/node_modules/source-map/lib/binary-search.js:59:14)
```

**Comment by fitzgen** [comment]
Can you provide a minimal test case and steps to reproduce this issue? Without that, this issue is not actionable.

**Comment by FTAndy** [comment]
this bug is fired in production, i cannot reproduce it in development. but i am sure the binary search function has some issue.
