### ISSUE TITLE
TypeError: aSourceMapConsumer.eachMapping is not a function

### ISSUE THREAD

**Issue by tommai78101** [mozilla/source-map#434]
I'm getting the following error when attempting to build a default "Hello World!" Angular application. I'm wondering if this is the place to report this issue.

```
[INFO] TypeError: aSourceMapConsumer.eachMapping is not a function
[INFO]     at Function.fromStringWithSourceMap (/home/tommai/projects/angular/node_modules/source-map/lib/source-node.js:87:24)
[INFO]     at SourceMapSource.node (/home/tommai/projects/angular/node_modules/mini-css-extract-plugin/node_modules/webpack-sources/lib/SourceMapSource.js:32:25)
[INFO]     at /home/tommai/projects/angular/node_modules/mini-css-extract-plugin/node_modules/webpack-sources/lib/ConcatSource.js:59:50
[INFO]     at Array.map (<anonymous>)
[INFO]     at ConcatSource.node (/home/tommai/projects/angular/node_modules/mini-css-extract-plugin/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
[INFO]     at ConcatSource.proto.sourceAndMap (/home/tommai/projects/angular/node_modules/mini-css-extract-plugin/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
[INFO]     at CachedSource.sourceAndMap (/home/tommai/projects/angular/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:58:31)
[INFO]     at getTaskForFile (/home/tommai/projects/angular/node_modules/webpack/lib/SourceMapDevToolPlugin.js:65:30)
[INFO]     at /home/tommai/projects/angular/node_modules/webpack/lib/SourceMapDevToolPlugin.js:215:20
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at /home/tommai/projects/angular/node_modules/webpack/lib/SourceMapDevToolPlugin.js:186:12
[INFO]     at SyncHook.eval [as call] (eval at create (/home/tommai/projects/angular/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
[INFO]     at SyncHook.lazyCompileHook (/home/tommai/projects/angular/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
[INFO]     at /home/tommai/projects/angular/node_modules/webpack/lib/Compilation.js:1413:42
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tommai/projects/angular/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (/home/tommai/projects/angular/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)


```

Node version: v14.16.0 (LTS)
NPM version: 6.14.11
Angular version:

```
Angular CLI: 10.2.3
Node: 14.16.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1002.3
@angular-devkit/core         10.2.3
@angular-devkit/schematics   10.2.3
@schematics/angular          10.2.3
@schematics/update           0.1002.3
```

**Comment by jkrems** [comment]
Since this is happening multiple levels into using different libraries - is there a repro we could look at (e.g. a gist or a Github repository)? Without that it will be hard to tell if it's related to `source-map` or something else.

**Comment by tommai78101** [comment]
There seems to be an update on the angular/cli webpack. I can't seem to reproduce the issue anymore.

I'm going to close this issue. If I were able to reproduce it, I'll try to attach a sample code. Thanks for looking into this.
